(require 'web-mode)
;(setq web-mode-markup-indent-offset 2)
;(setq web-mode-code-indent-offset 2)
(add-to-list 'auto-mode-alist '("\\.jsx$" . web-mode))
(add-to-list 'auto-mode-alist '("\\.htm[l]?$" . web-mode))
(defadvice web-mode-highlight-part (around tweak-jsx activate)
	(if (equal web-mode-content-type "jsx")
			(let ((web-mode-enable-part-face nil))
				ad-do-it)
		ad-do-it))
(defun my/web-mode-hook ()
  "Hooks for web mode."
	(local-set-key (kbd "RET") 'newline-and-indent)
	(setq web-mode-html-offset 2)
	(setq web-mode-css-offset 2)
	(setq web-mode-script-offset 2)
	(if (equal web-mode-content-type "html")
			(lambda ()
				(require 'rename-sgml-tag)
				(define-key web-mode-map (kbd "C-c C-r" 'rename-sgml-tag)))))
(add-hook 'web-mode-hook 'my/web-mode-hook)

(setq web-mode-enable-current-column-highlight t)
(setq web-mode-ac-sources-alist
			'(("css" . (ac-source-css-property))
				("html" . (ac-source-words-in-buffer ac-source-abbrev))))
(provide 'setup-web)
